a.Импортируйте библиотеку NumPy

j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

Импортируйте библиотеку NumPy b.Создайте массив из 10 нулей

In [ ]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


a.Импортируйте библиотеку NumPy c.Создать массив из 10 единиц

In [ ]:
import numpy as np
a=np.ones(10)

print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


a.Импортируйте библиотеку NumPy d.Создать массив из 10 пятерок

In [ ]:
import numpy as np
my_list = [5,5,5,5,5,5,5,5,5,5]
print(my_list)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


a.Импортируйте библиотеку NumPy e.Создать массив из целых чисел от 10 до 50

In [ ]:
import numpy as np
a=np.arange(10,51)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]



a.Импортируйте библиотеку NumPy f.Создать массив из четных чисел от 10 до 50


In [ ]:
import numpy as np
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


a.Импортируйте библиотеку NumPy g.Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
import numpy as np
arr=np.arange(0,9)
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


a.Импортируйте библиотеку NumPy h.Создать единичную матрицу 3x3

In [ ]:
import numpy as np
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


a.Импортируйте библиотеку NumPy i.Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
import numpy as np
a=np.random.rand(1)
print(a)

[0.88165548]


.Импортируйте библиотеку NumPy j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [ ]:
import numpy as np
##статистика
arr=np.arange(0,25)
#print(arr.mean())
#print(arr.std())
#print(arr.var())

print(a)


[ 5 48 54 55 83 93 71 86 67 28 23 28 63 53 74 53 23 92 82 52  4 80 60 83
 52]


k

In [ ]:
import numpy as np
x=np.arange(0.01, 1.01, 0.01)
b=x.reshape(10,10)
print(b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


l.# это наша стартовая матрица mat = np.arange(1,26).reshape(5,5)
print(mat) Необходимо написать код который вернет следующую матрицу
из стартовой от 12 до 25

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------

print(mat[2:,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Написать код обращения к элементу который вернет значение 20 из
стартовой матрицы задачи l.

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------
print(mat[3,4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
20


Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже
2
7
12

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------
print(mat[0:3,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  7 12]


Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже 
21 22 23 24 25

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------
print(mat[4,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[21 22 23 24 25]


Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже
16 17 18 19 20
21 22 23 24 25


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------
print(mat[3:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[16 17 18 19 20]
 [21 22 23 24 25]]


Получить сумму всех значений в стартовой матрице mat

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------

print(mat.sum())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
325


Получить стандартное отклонение в стартовой матрице mat

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------

print(np.std(mat))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
7.211102550927978


Получить сумму значений в колонках в стартовой матрице mat

In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)
#-----------------------
print(mat.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[55 60 65 70 75]
